name: Build and Release Windows

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build-release:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.head_commit.message, 'release ')
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Restore NuGet packages
        run: nuget restore ToNRoundCounter.sln -ConfigFile NuGet.config
      - name: Build
        run: msbuild ToNRoundCounter.sln /p:Configuration=Release /p:Platform=x64
      - name: Include updater
        run: Copy-Item -Path .\Updater\bin\Release\net48\* -Destination .\bin\x64\Release\ -Recurse -Force
      - name: Include shared assets
        run: |
          Expand-Archive -Path share_assets.zip -DestinationPath share_assets
          Copy-Item -Path share_assets/share_assets/* -Destination .\bin\x64\Release\ -Recurse -Force
      - name: Collect modules
        run: |
          $modulePackagePath = Join-Path $PWD "ModulesPackage"
          if (Test-Path $modulePackagePath) {
            Remove-Item -Path $modulePackagePath -Recurse -Force
          }
          New-Item -ItemType Directory -Path $modulePackagePath | Out-Null
          Get-ChildItem -Path .\Modules -Filter *.csproj -Recurse | ForEach-Object {
            $projectDirectory = $_.DirectoryName
            $moduleName = $_.BaseName
            $moduleOutput = Get-ChildItem -Path (Join-Path $projectDirectory 'bin') -Recurse -Filter "$moduleName.dll" |
              Sort-Object LastWriteTime -Descending |
              Select-Object -First 1
            if ($moduleOutput) {
              $outputDirectory = $moduleOutput.Directory.FullName
              $destination = Join-Path $modulePackagePath $moduleName
              New-Item -ItemType Directory -Path $destination | Out-Null
              Copy-Item -Path (Join-Path $outputDirectory '*') -Destination $destination -Recurse -Force
            }
          }
      - name: Package
        run: Compress-Archive -Path .\bin\x64\Release\* -DestinationPath ToNRoundCounter_latest.zip
      - name: Extract version
        if: github.event_name != 'workflow_dispatch'
        id: get_version
        shell: bash
        run: |
          MESSAGE="${{ github.event.head_commit.message }}"
          VERSION="${MESSAGE#release }"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Create Release
        if: github.event_name != 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          files: |
            ToNRoundCounter_latest.zip
            ModulesPackage/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
